---
title: "多层次调控与跨领域治理：语言政策的社会政治关系协调功能和作用研究"
# author:
# - 胡悦
# - 朱萌^[胡悦，清华大学政治学系副教授；朱萌，通讯作者，清华大学政治学系博士研究生。]

output:
  word_document: default
fontsize: 12pt
bibliography: language_governance.bib
csl: american-political-science-review.csl
link-citations: no
colorlinks: yes
abstract: |
 
 **摘要**：
 
 **关键词**：语言治理 
 
 **Abstract**: 
 
 **Keywords**: Language governance  
---

# 引言

妥善协调民众的社会政治关系，使相互冲突的或不同的利益群体得以调和并且采取有序行动，是政治治理和社会治理的核心任务，也是现代社会实现稳定发展的重要前提[@JiangXiaoPing2014]。
语言则是实施社会政治关系协调的重要媒介；诸多关系协调手段多种手段，如政民互动、社会动员、媒体宣传等，都需要基于语言方能实现[@MillerRose1990]。
然而，对于语言政策，这一塑造国家语言结构、指导社会语言秩序的重要公共政策工具，在调整社会政治关系上的功能和作用，仍缺乏系统的分析和讨论。
同时，国民的社会政治关系既包含个体与自身生活环境的关系，也包含群体与群体间关系以及公民与政府的关系。
多数治理工具仅能施为于特定层级或者领域的社会政治关系，而后文则将指出，基于语言政策的治理方式（即“语言治理”）具有多层次调控与跨领域治理特性，有助于对民众社会政治关系的系统性协调和引导。


本文在总结国内外政治语言学和社会语言学既有研究成果基础上，讨论语言治理在调整个体、群体和国家三层次社会政治关系中所扮演的重要角色和影响路径。
本文指出，语言对国家治理、群体治理和改善发展环境具有十分重要的功能，能够增进国家认同、群体团结、增强社会公众政治心态的积极面向和稳定程度。
本研究进而提出了语言治理的实施途径，通过调节族群关系、规范语言政策、加强心理引导，达到对个体、人际、国家社会政治心态的全方位调控。
语言治理是实现社会平稳过渡、增强社会融合、巩固良性群体间关系的长效机制。
研究还提出了新时期以来语言对于我国城市治理、乡村振兴、新媒体治理的调节作用。
本文最后指出，只有制定正确的语言政策才能够解决新时代我国发展面临的一系列问题。

实现对公众政治社会心理的同步调节，从而为新时期我国所面临的治理问题和治理需求提出语言学的治理方案，为更进一步地实现“共建、共治、共享”的社会良性发展和制度建构提供借鉴思路。



# 语言在政治治理中的角色与功能

语言作为人类最重要的交际与思维的符号体系，是传递信息与价值，交流思想与情感，认知世界与社会的工具，是组织社会、承载文化、提升认知、发展经济的有效途径。
不同视角、不同学科对其功能与作用给予了各种不同的阐释。
如，经济学家有关语言技能是一种经济优势的观点[@LiangEtAl2018]；
社会学家强调语言的个人性与社会性[@DuMinLiuZhiGang2020]；
政治学家认为语言与国家构建息息相关[@Benedict2005]。
虽然有关语言的功能和作用在各社会面向和议题上均有反映，但从研究视角上，可归纳为三个维度：

## 语言与国家治理

国家治理是国家政权的所有者、管理者和利益相关者等多元行动者在一个国家的范围内对社会公共事务的合作管理，以维护公共秩序、增进国家利益、实现社会团结[@HeZengKe2014]。其中，语言是影响治理有效性和执政合法性的关键性因素[@Hu2020]。
政治生活中，国家通过合理安排语言政治权力，实现语言政治权力的善治，因而语言治理需要乃至必须体现政治的立场和政治的高度。
具体而言，主要体现在国家通用语和方言两个方面：

国家通用语言对于加强国家整合和塑造民族认同具有重要作用。
国家通用语言的掌握消除了各地区和各民族因语言差异带来的不安，消弭了地域保护主义，加强了各民族、各地区经济文化的交流，进而构建了统一的民族或国族身份，促使各民族产生想象的共同体，维护了国家统一和民族团结[@ZhangWeiGuo2020;@HuangShaoAnWangLuCong2020]。

从秦始皇统一文字到汉武帝独尊儒术，从孝文帝“断北语，从正音”到隋文帝科举选拔，从宋代《广韵》、明代《洪武正韵》到清代“以官音统一天下之语言”、民国时代“国语运动”“白话文运动”，再到新中国的推广普通话、简化汉字、汉语拼音方案推广、语言文字信息化、语言文字法律法规体系、微语言治理等。上述波澜壮阔、传承延绵的中华语言治理历史无不表明了语言是国家认同建构的重要对象和核心构成要素。

民族国家通常会以不同的方式制定各类语言政策，实施语言规划，配合语言民族主义或语言爱国主义，以此巩固、发展和强化公民的国家认同。

从语言功能的角度来看，对于地方治理和基层治理而言，方言和民族语言有助于加强政策宣导效果，提高官民沟通效率。
交际便利与否是语言使用的关键因素，国家通用语言使用的便利性低于方言和民族语言[@LiuHuaXiaYuanQingHuan2017]，在少数民族聚居使用民族语言或者在地方使用方言更有利于政策的传达和民众的理解。

以汉语为例，有官话、晋语、吴语、闽语、粤语、客家话、赣语、湘语、徽语、平话和土话等十大方言，还可进一步细分为97个方言片，101个方言小片。
很多方言土语之间无法通话，尤其是在条件艰苦的偏远山村，普通百姓在日常生活中仍较多使用方言交流。
如果国家机关在执行公务或者广播电视等大众传播媒介在进项宣传时，采取本地人用本地话讲本地事的形式，更易达到预期效果。

面对多数国家内部语言方言差异巨大的客观事实，包括方言在内的各类语言成为国家治理中不可或缺的一部分，因语言沟通障碍而影响了地方政府工作开展并引发对语言服务的需求，已成为亟需解决的问题。
但方言对地方保护主义以及民族语言对分裂势力的影响不容小觑，我们也需时刻注意分裂型语言民族主义[@ChenPing2008]。

总之，国家通用语作为国家记忆和文化的主要载体一直以来受到各国政策制定者的关注和争相推广。
国族的共同记忆、历史传统、文化、价值等要素的培育和传递，都需要统一的民族语言作为基础[@Anthony2002]。
如，先秦的雅言、汉魏的正音、隋唐的雅韵及字样、宋元而至明清的官话以及近现代的国语和普通话等语言治理之策就一直是中国国家治理的重要组成部分。

与此同时，方言和民族语言作为一种语言力量，是一把双刃剑。既可以有效传达政治信息和推动政策目标的实施，从而提高地方治理绩效；也可以被用来实施民族分裂和种族异化、谋取不正当利益，成为民族运动领导层得心应手的政治工具[@DaiManChunZhuNingYan2011]。


## 语言与群体治理

上述有关语言政策和语言治理的研究主要从宏观角度出发，停留在语言对国家认同、政治秩序的塑造与国家治理能力上。
实际上，国内外也有大量学者探讨了语言治理对群体心理方面的重要作用，强调语言是建构社会身份认同和划定群体边界的重要指征。

群体治理强调民众的自我管理能力，指在没有政府的参与下，通过自我协作、信任关系、社会交往以及非正式协议等自治手段，以自下而上的权力运作方式来管理社会团体和社会组织[@Ostrom2015]。
现实利益理论（Realistic Interest Theory）提出，个体通过人际互动塑造群体利益（shared interests）。
而语言对于满足人际交往和社会互动的紧迫需求，在更广泛意义上团结松散民众，形成集体凝聚力和阶层共识发挥着重要作用。

语言在被认为是厘定文化群体(cultural communities)边界的核心指标。
社会成员可以利用外貌、仪式、行为等多种方式彰显群体归属，但人类社会自古以来最简单也是最有效表明自己身份和判断他人身份的手段就是语言，并且可以通过学习一门新的语言改变或提高自己的身份[@WangKeFei2011]。
人们在听到某种特定语言类型后，会由此对语言使用者产生一些直观感受和印象[@LiuHong1993]，即对不同种类的语言类型使用人群具有不同的感情和态度差异。
@LiuHuaXiaYuanQingHuan2017  就基于对不同个体语言能力差异的研究指出，语言差异会影响群体之间的相互认同，乃至形成心理隔阂，从而造成社会认知和社会判断的固化。
因语言而划定的群体边界，使人们在心理和文化上对“我者”与“他者”做出判断，即对属于本群体内部的人有着较高的信任，更能相互包容和团结，更能遵守群体规范，从而有利于破除集体行动的困境。

国外移民研究也表明，语言是社会融合的前提条件，是正式进入的必备要求。
如果人们持有不同语言即不会相互融入，同时还会体验到来自主流社会的敌意和排斥，因此由自身母语方言到当地方言的转变被看作是移民文化适应和社会融入的关键标志[@RendallEtAl2010;@DustmannFabbri2003]。
在这种意义上，对通行语和流行语的掌握程度也就塑造了社会个体对于主体社会的融入程度。
@VroomeEtAl2013  通过对美国移民和少数族裔的研究发现掌握英语更好的少数群体的社会融入程度往往更高，这表明语言对少数族群融入主流社会的意愿能够产生显著的影响。

## 语言与个体治理

@Giddens2000 认为，个体治理包含“解放政治”和“生活政治”的双元混合，前者是关于对社会地位和社会权利（力）的争取，而后者则偏重于对社会认同和自我实现的追求。

当前，中国社会结构发生巨大变革，场域的改变使得传统社会对个体治理的运作路径面临极大的挑战。
个体的话语表达、经济活动、自我组织和自我管理等空间被逐渐释放出来，个体的自主意识、权利意识和竞争意识日益增强。

现代性社会的时空分离与压缩的特征以及在此基础上形成的个体“脱域”与“延异”现象[@Giddens2000]，造成个体治理的“内卷化”和“无根化”。

可见，以个体利益、个体成就为导向的价值追求导致中国传统社会一直以来的集体化治理模式和治理框架逐步瓦解[@HongBo2018]。

而语言作为重要的资本符号，能够伴随文化资本、经济资本和社会资本参与到资本转换中[@YingJiZhuoMa2018]，对个体能力和个体认知产生重要影响。

就个体能力而言，人力资本理论和教育经济学理论普遍认为，语言作为人类经济活动工具，在信息传递上具有价值、效用、成本和收益等经济特性[@ZhangWeiGuo2011]。
成本——收益视角下的语言能力，是对个体信息获取成本和信息获取能力的考量；
一种语言掌握越好，信息沟通成本越低，信息收益越大，个体越容易了解与掌握相关的政治、经济、法律等社会生活中的知识和惯例[@ZhangWeiGuoSunTao2016]。

社会语言学也表明，掌握一门语言能够有效提高个体在获取信息和资源的能力，获取更多的公共资源和发展机会。
实证研究显示，语言水平相对较高的人群由于交流障碍更少，且拥有更好学习新技能和表现自身能力的交流工具，因此更受人才市场青睐。这类人群因而在社会中更具有竞争力，更有可能适应现有的生活环境，攀升到较高的社会地位；其个人社会定位也更为稳定。

提高个体的语言水平，促进个体之间的交往互动，有利于创造良好的人际关系、生活环境和工作环境，提高个体的社会适应能力、影响力、竞争力和资源获取能力。

从个体认知来看，语言与自我认知塑造相连接。
具体而言，由于人们对于自我的定位很大程度上是在与他人接触后的内省获得的。
个体对于主流语种掌握能力越突出，其社会融入和社会经济生活就越顺畅，交流成本就更低，相应的在拓展人际网络中的阻碍也更少，更利于个体融入当地社群，因而对自身和社会的评价也就越高。
当一个人擅长并非所有人都掌握但又普遍认同的语言（如一种通用语），语言就成为证明其能力的依据；语言掌握程度越高，其自我认同和自信也就越强。
譬如，@QiHongLiHong2004 对语言学习者自我认知的研究表明，语言能力的提高对个人自信心具有显著的积极作用。
更进一步，在学习语言的过程中，学习者不仅内化了语言能力，还在与目标文化的交互中，在某种文化生态之下完成意义建构或意义生成，从而实现了自我建构和自我评价的提高[@SuFang2020]。
相反，语言掌握程度低会使使用者的自我评价也随之降低。
@WrightTaylor1995 就发现在母语教育对少数民族儿童的学业和心理发展的研究中发现，少数民族学生在不熟悉教学语言情况下，极易导致自信水平下降，从而持有更多的消极自我评价。

# 语言治理的实现途径

上述讨论呈现了语言治理对国家、社会群体及公众个人政治社会心理的多维度、多层次影响。
而作为治理者，如何有效实施和推行语言治理，最大化其治理效能呢？回答这一问题需要对语言治理的实施途径进行深入全面理解。
本文主要从阐释政策规范、调整群体关系和改善发展环境三个方面来探讨语言治理的实现机制。	

## 阐释政策规范

语言政策是语言生活领域的国家意志体现，是国家在语言生活领域的治理方案，不仅对人们的社会地位认知、社会融入程度，社会参与意愿具有导向作用，还会直接影响民族关系、社会稳定、经济发展模式。
因此，国家会有目的、有计划、有组织地对语言文字及其使用进行干预与管理，通过立法或者政府调节手段，使语言文字更好地为国家服务[@DaiManChunHeZhanRu2010]。

作为政治问题的语言政策，各国的价值取向和路径模式不尽相同。
如，十月革命后，苏联将大多数语言的文字系统改换成拉丁字母文字，包括为少数民族创制的拉丁化新文字；越南民主共和国成立后，即宣布拉丁字母的越南文为“国文”，彻底废除了传统社会长期使用的汉文和喃字；北朝鲜独立后，也彻底废除了传统社会长期使用的汉文而改用谚文，即现今的朝鲜文[@MaRong2004a]。

可见，各国政府努力促进语言政策的本土性转化，在立足具体国情的基础上制定出符合国情的语言政策，，从而促进本国经济发展、推动民族融合。

不仅如此，传统的政治经济学和族群政治也从政策成本、族群权力、迁移风险等诸多方面探讨过语言政策对族群稳定、经济发展和政策制定等政治结构和决策的影响，强调语言政策在跨族群社会和国际交往中的作用[@CookLiu2016;@LiuPizzi2018]。
例如，@Liu2015 将语言政策以是否为主体民族语言和是否存在多官方语言两个维度划分了四类，发现四种语言政策对国内族群互动、国家对外交往、投资引入的对外资本均有重要影响。
这类研究也在实践中得到了证实。
非洲新兴独立国家领导人在构建国家认同和民族意识过程中，十分注重语言政策在社会成员族群意识、国家身份、社会经济发展等多个层面对该国的社会经济制度的参与塑造作用[@Laitin1977]。
法国历代政府相继成立诸如法兰西学院、法语和方言总署等有关机构，对法语进行语言规划并大力推广，强硬语言政策的长久推行提高了法语的普及率，为国家的统一性、国族的认同以及国民经济发展发挥了重要作用[@DaiManChunHeZhanRu2010]。

## 调整群体关系

语言平等是族群平等的重要内容和重要标志之一，国家会通过规定各族群所使用的词汇和语言，并通过这些词汇和语言控制改变着其交际行为，借此加强各族群在政治、经济、文化以及情感方面的联系[@KathrynKendall2017]。

一直以来，语言政策作为国家民族政策的重要组成部分，各国政府就不断强调语言政策要体现出少数族群的“心理状态”，达到维系民族团结的目的。
1968年美国《双语教育法》的通过便是承认美国语言多元化的事实，即存在一些母语不是英语的学生（或成人）。这一法律的颁布部分地解决了多族群间的语言矛盾和语言冲突，维护了国家和社会的稳定。

瑞士是世界上惟一将国内各族群语言都定为国语的国家，规定所有语言都具有平等的法律地位[@MengHongLi2010]，高中学生均要学习三种官方语言(德语、法语、意大利语)。
这一政策的实施使得瑞士因而被认为只是一个“具有文化差别性的社会”，而非是一个“多数族群－少数族群共存的社会”，从而避免赋予族群差异以任何其他的政治和意识形态出现或加深，实现了多民族社会的稳定团结。

中国的社会制度与民族政策一直面临着西方国家提出的“对少数族群实行同化政策”的舆论批评和外交压力，但中国宪法和相关法令实际上明确规定了各少数族群都有使用和发展其语言文字的自由。
中国的语言使用情况由此呈现出“多元一体”的格局——各个族群保存并发展自己的语言，以维护本民族文化。
同时，各个民族又将汉语作为全国通用的“族际共同语”，以促进各族群间的交流沟通和全国范围内经济、文化等各方面事业的发展。

值得注意的是，过分强调民族语言在国家社会和公共事务中的地位和作用在客观上也将会导致民族隔绝的非意图后果，致使语言成为某种特殊的族群象征，演变成具有特殊实用意义的工具，阻碍了各族群间的相互学习与交流[@MaRong2017]。

实际上，语言具有文化象征和交流沟通的双重属性。前者带有深厚的历史感与情感色彩，后者则强调语言是功利性的交流与学习工具。
因此，在政治平等的意义上解决了各族群语言问题的合法性后，应当从应用性的角度实事求是地分析，利用市场经济逐步推动共同语言作为交流工具，打造在经济层面上能够加强各民族间分工合作和降低成本的政治地理区域。

## 加强个体治理

人们的思维依赖于框架、原型、隐喻、意象等语言和认知手段。
国家通过控制、筛选、组织和分配话语的生产，并借用语言符号来把握微观个体的具体话语行为，潜移默化地加强语言与个体身份的良性构建，从而实现对个体心理的有效引导。

当前，随着新信息技术和电子媒介的出现，政府通常将媒体作为实现实际言语交际和经验表征的工具，新闻话语及图像根据政治需要或意识形态的准则而被选择、建构和处理，以便合法化政府行为。

具体而言，国家借用多模态话语——语言文字、图像和图表的复合话语构建社会现实的人际互动，利用各种符号模态协同作用下构建的现实意义，引导民众心理。

如，@DingJianXinYangHui2020 分析了新冠肺炎爆发时美国媒体如何借用图像、语言来比喻政治，将单纯的医学名词赋予道德批判意义和政治化立场，塑造和加深了美国民众对中国的敌意。美国媒体和政治家在大量的新闻标题和政治评论中以“Wuhan Coronavirus”或者“Wuhan Virus”来称呼新冠病毒，甚至出现“黄祸”“中国病毒”等词，引导美国民众寻找、建构另一个“他者”，并将罪责归于“他者”，以缓解自身的恐惧和焦虑，进而作为一种政治延伸达到影射中国的目的。

对于同一个客观事物，不同的语言表达会产生不同的效果，并演绎出不同的游戏规则和行事逻辑。亚里士多德的《修辞学》和西塞罗的《论演说术》也无不强调话语是构建民众世界观和概念化政治问题的一种重要手段。

如，针对当前气候变暖问题，美国前副总统戈尔通常使用“气候危机”(climate crisis)或“气候混乱”(climate chaos)，而前总统小布什在其国情咨文中坚持使用“气候变化”(climate change)及“全球变暖”(global warming)。相比之下，“气候危机”和“气候混乱”明显强化了该问题的严重性和必须采取措施应对的紧迫感。而“气候变化”或“全球变暖”则将公众的注意力框定在全球平均气温上，认为该问题可控且尚未对人类形成太大的挑战，进而不去关注更为严重的诸如海啸、水灾及旱灾等环境问题。


# 语言治理与新时期中国政治发展

以上三种实现途径构成相互关联、相互影响、有机统一的语言治理体系，对国家稳定、民族团结、社会成员个体发展、和谐社会氛围建立和延续、良好政治秩序的巩固和维持，均具有长期且深远的影响。

当前，我国正处于经济发展方式和社会治理模式的双重变革时期。
变革所带来的一系列社会结构和治理策略变，均对国民政治社会心理产生巨大影响。
相应一系列问题也随之凸显，比如，由于经济结构剧烈变化而导致的国民自我定位错位[@JingHuaiBinEtAl2017]，由于人口结构变化和加速城镇化带来的人际信任缺失和新、老市民身份认同矛盾[@LuHuiLinPanYi2014]，以及人民日益增长的政治参与需求与政府治理方式的不匹配等问题，都成为当代中国社会急需关注的问题。
如果处理不当，将极易造成民众情绪激化，甚至演变成恶行群体事件，损害社会稳定，威胁正常政治经济秩序[@HaoYuQingCheYue2011]。
然而，这些问题的产生很大程度上与语言距离和语言区隔密切相关，语言具有强烈的社会识别功能，对于打破群体隔阂，促进社会公众的心理融合具有重要的作用。
上述问题迫切需要国民具备较好的沟通能力和较高的语言文字应用水平，提升自身的综合素质，以便更好地融入主流社会。
我国的语言治理借助以上三种实施途径，从具体国情出发，呈现出了独特的治理面貌。

## 城市治理

在新时代国家治理与城市治理的理念推动下，城市语言治理能力与治理能力现代化逐步成为城市研究的新任务。
就时间维度而言，城市语言治理包括常态性问题和应激性问题两部分。

长远看来，如何实现以“人的城镇化”为核心的新型城镇化建设，处理好人与语言、语言与社会、语言与语言、语言与方言、语言与社团之间的关系，成为当前城市治理和区域发展的新痛点和新难点。
中国城市化进程全面提速，国家统计局最新发布的关于2019年国民经济和社会发展统计公报显示，我国城镇常住人口已达84843万，城镇化率为60.60%，已经超过世界平均水平[@ShenQi2021]。
城镇化的发展促成了频繁的人口流动，导致国内出现了大量的新市民或流动人口。
而无论是农民工还是城市新市民，他们必然带来语言的接触与融合，导致语言地图的变更。
方言与其他正在逐步逝去的乡土生活和文化记忆一起，均在经历着一个前所未有的极速变异过程——亦或是在当地语言之外形成了“方言岛”，亦或是产生了新的语言变异和变体[@WuXiaoJun2020]。
这一过程导致了大量人群失语、失权、失利。

传统治理视角认为，对于城市主体人群和新进人群/少数人群的隔阂和矛盾，主要通过增强后者社会融合度（比如农民工的城市化程度或少数民族的融入感等）等加以改善。
但上述局面使得语言在城市治理中的协调与中介价值日益凸显。
快速城镇化和区域一体化作为新时代中国发展的核心特征之一，现有政府正在通过语言治理促进社会公众心理融合，提升全体公众人际信任和积极心态，为营造和谐社会氛围搭建心理基础，实现普通话、方言和外语和谐共生，助力新型城镇化人本目标的实现。

就当下而言，新冠疫情的暴发使得城市语言治理能力不足的问题充分暴露出来[@ShenQi2021]。
2020年上半年，我国大城市疫情防控工作中暴露出一系列涉外语言能力不足以及涉外语言治理空白等问题。
当前国内大城市仍未建设或运行语言人才资源数据库或语言志愿者信息库，严重影响城市在突发重大事件中的涉外应对能力、效率和速度；
城市的语言翻译和语言服务中对于外语语种的设置和提供多少有些随意，缺乏深谋远虑，政府和公共服务机构的语种规划与多语意识亟待全面加强；
政府多语信息发布和服务渠道的社会影响力和可及性均不令人满意；
面对大量的在华外国人，尚未形成有效的语言服务协调机制和语言治理体系，各类事务由分散在各政府部门的机构或基层组织自身来解决，缺少有效的合作治理机制。

这些问题都提醒我们，我国大城市语言治理能力亟须提升，后疫情时代城市化建设中纷繁复杂的语言治理问题需要更加引起重视，系统探索“自上而下”与“自下而上”双向互动的城市语言治理体系，正当其时。

## 精准扶贫与乡村振兴

乡村振兴是党的十九大明确提出的一项国家战略。
2018年9月,中共中央、国务院印发了《乡村振兴战略规划(2018—2022年)》，强调防止因语言能力的缺乏和语言上的弱势致贫返贫，减少语言藩篱对贫困地区发展的束缚，注重语言政策与规划在乡村振兴中的作用。
精准扶贫战略下地的语言扶贫虽已取得显著成效，但语言资源的差异仍会导致个体机会的不平等和社会阶层的差距。
聚焦于精准扶贫而实施的语言扶贫如何适应新战略对语言服务社会和国家的总体要求，如何实现语言治理在精准扶贫与乡村振兴战略的顺承与衔接成为中国国家治理的重点工作，也是当前亟需回答的问题[@DuMinLiuZhiGang2020]。

基于此，我国现有关语言治理对乡村振兴的作用主要基于以下两点：

首先，推广普通话对乡村振兴具有促进作用。
通过提高少数民族贫困人口使用普通话的能力及该地区普通话的普及率，构建沟通桥梁，打破贫困地区和外界信息交流的语言屏障，从而推动贫困地区经济发展[@LiYuMing2018]。
如，建立以“普通话专项培训为重点，以送培下乡、送教上门的农民夜校、普通话与使用技能培训相结合等方式为主，以其他各类语言文字培训向贫困地区倾斜为补充”培训体系[@TianXueJun2019]；
编写推普脱贫入门教材，教育部语用司先后赴四川凉山州、甘肃临夏州东乡县等深度贫困地区进行调研，征求意见，组织专家编写《普通话1000句》，结合纸本教材，录制音频、微课，制作语言游戏[@DuMinLiuZhiGang2020]。
这些政策旨在提升乡村地区，尤其是民族地区普通民众的基本交际能力和沟通能力，帮助当地居民树立自信心和自强自立精神，从而内在地、主动地改变贫困落后的生活状态和面貌。

其次，以振兴乡村文化为要旨，注重多样化语言文化的保护。
通过对少数民族地区当地语言的规划和管理，发掘少数民族语言的本体资源[@SuDe2004;@LiuHuaXiaYuanQingHuan2017]。
如，鼓励和支持各地筹建本地语言文化资源库和语言博物馆、建立地方语言资源平台、举办方言微电影、推动以图、文、音、像、影多种形式全方位展示和利用我国语言方言文化资源，从而形成了推广普通话和保护少数民族语言互促互补的良好局面。

我们已清晰地认识到了语言的扶贫功能，为贫困人口和贫穷地区修筑起脱贫的语言大道，改变了经济劣势和发展劣势、促进了当地社会的文明进步。
但乡村振兴战略下语言治理的发展目标和任务有所不同。
乡村振兴下的语言治理增添了更多的使命与任务，以实现其在新时代的新职能，实现语言扶贫的可持续发展。
即除“推普脱贫”彰显其工具性的语言扶贫功能外，仍需不断丰富语言扶贫的内涵，不断克服语言因素对乡村地区全面发展和现代化所产生的阻碍，进而促使其不断提高生产、生活和内生性发展的能力，进行语言文化的振兴，语言生态的保护，语言资源的开发，真正实现乡村的人才振兴、文化振兴和产业振兴。


## 新媒体治理

媒体是现代社会信息的主要提供者，发挥着重要的社会功能。
作为宣传国家语言文字规范标准的重要窗口和践行者，是国家语言规划的关键领域[@ChenLiXiang2021]。

随着人工智能、大数据、云计算、区块链等新一轮新技术的飞速发展，移动应用、社交媒体、网络直播、短视频等新应用、新业态的不断涌现，国内新媒体用户数量的激增和其信息传播能力的突显正全方位地重塑媒体格局和社会生态[@TangXuJunEtAl2019]。

依据中国互联网络信息中心(CNNIC)数据，截至2020年3月底，我国网民规模达9.04亿，与2018年底相比增加了7508万；互联网普及率达64.5%，较2018年底提升了4.9个百分点。
我国新媒体的发展出现了井喷态势，根据Statis官网的数据，微信及WeChat活跃用户量在12.03亿以上，抖音及TikTok活跃用户量在8.01亿以上，QQ、新浪微博活跃用户量均在5亿以上[@LiSongLin2021]。
这一新的态势和格局使得媒体的语言文字行为将形成范围更广阔的社会示范效应；但其巨大的活跃性能也在一定程度上改变着语言文字的生态，给新媒体语言治理带来新的问题。

据此，规范用字用语是我国对新媒体实施语言治理的核心议题。
现有政策主要从社会用字角度，围绕核心议题的“新媒体语言文字使用规范性”来开展，重点规划和解决国家通用语言文字使用、方言使用以及新词新语规范等问题[@ChenLiXiang2021]。
例如，自2001年起实施的《中华人民共和国国家通用语言文字法》是我国第一部语言文字专门法律，成为媒体语言政策相关的地方性法规、行政法规和部门规章的重要参照。
此外，《国家新闻出版广电总局关于规范报刊单位及其所办新媒体采编管理的通知》(2017)、《网络视听节目内容审核通则》（2017）等专门性法律法规均强调“新兴媒体不仅要发挥充分语言的吸引力和传播力，也要发挥语言文字对发展积极向上的网络文化、净化网络环境的重要作用”。
这些具有针对性的语言政策及规范为我国新媒体行业的语言文字使用提供了切实可行的规范。

信息技术的变革使得新媒体的语言影响力正在超越传统媒体，进而导致新媒体广泛参与社会治理的同时，其自身也成为社会治理的一环[@LiSongLin2021]。
我们现有的以传统媒体为主要治理对象的媒体语言政策，需要更多关注新媒体时代的语言和语言生活，积极统筹各方力量，使政府、社会、公众形成治理共同体，加强各主体之间的督促、衔接和协调，实现媒体语言治理的资源整合和力量融合，构建新媒体治理格局。

# 总结与讨论

本文从语言政治学视角归纳了语言公共政策对国家治理、群体治理以及个体治理的重要性，揭示了语言影响的长期性、广泛性和复杂性，呈现了语言政策和语言规划影响社会成员政治社会生活和取向的多层次、多面向影响，为我们在较大范围内从事理论概括和理论创新提供了坚实基础。

本研究归纳了语言治理的三种实施途径，即阐释政策规范、调整族群关系以及加强心理引导。
虽然有关研究已被语言学和教育学领域的学者所关注，但本文从政治学视角提供了有关语言治理的实现机制，体现了基于语言功能的不同治理策略，为思考如何切实实现民族平等、有效引导公民参与、提升治理效率、降低治理难度，提供新思路。

本研究从城市治理、精准扶贫和新媒体治理三个方面探讨了语言治理与新时期中国政治发展的关系，厘清当前国内语言治理的三个面向，这些梳理有助于加深对语言政治和语言政策的理解，为制定合理的语言、教育政策也提供了借鉴，在学术和治理实践上都具有重要启示：

首先，坚持党的领导。
语言治理是一个广泛的社会政治调控过程，其中包含对中国历史、中国国情、中国实践的全面把握，包括对各个国家机关、党政机关的动员组织，是带有全局性、战略性、根本性和长期性的重大任务，只有坚持党中央的集中统一领导，才能有效总揽全局、协调各方，制定正确的语言政策和语言发展战略，推进中国特色社会治理，构建良好社会氛围、稳定政治秩序，实现语言治理现代化。

其次，服务于国家总体目标。作为国家公共政策的组成部分，国家语言政策的制定及实施应基于国家治理理念和总体目标。
习近平总书记指出，要构建集政治安全、国土安全、军事安全、经济安全、文化安全、社会安全、科技安全、信息安全、生态安全、资源安全、核安全等于一体的总体国家安全观。本研究揭示，语言安全不仅是文化安全的重要组成部分，更对政治安全和社会安全具有重要影响。这我们需要更加全面地研究公众语言政策（包括公众外语政策、民族语言政策）对于国家治理的影响，探讨语言政策有效促进国家治理的可能形态，使语言政策更好地为国家总体目标的实现服务，为中华民族共同体和人类命运共同体的建构贡献更多力量。

再次，注重群体身份塑造。语言是最重要的群体属性之一，能够凝聚和强化群体意识，增强群体认同感。
当前，社会分化严重、社会矛盾突出，群体间对公共资源、国家机构，特别是语言政策控制权的争夺日益激烈，极其容易引发群体事件，影响社会秩序稳定。国家治理需要注重语言对群体身份的塑造作用，运用语言治理“润物细无声”的调控功能，对民众心理状态进行潜移默化而又具有持续性的调整和培养，调节个体社会成员的自我定位和人际关系，促进群体间心理融合，避免话语冲突导致严重的政治冲突。

最后，明确推广普通话的目的和效果。
对于中国这个多方言国家来说，普通话是进行现代国家治理不可或缺的语言工具，但一旦过分推行通用语，导致方言和少数民族语言式微，那么语言治理的效果也必会随之降低，尤其在地方意识或族群文化比较浓厚的地区，如果仅一味强调通用语，将很可能适得其反。并且，目前推广普通话只是聚焦于语音、语调层面的推广[@LuZiWen2008]，国民是否能从语义这个根本目的上理解通用语治理与方言保护之间的非对立性有待考察。这要求我们明确推广普通话的目的和效果，妥善处理推行通用语与保护地方方言、少数民族语言的关系，平衡建立低成本交流环境与合理利用地方文化资源的关系，切实保障语言权利，解决语言问题，构建和谐语言生活。

